# Generated by Django 5.1.5 on 2025-01-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeEditor', '0009_alter_currentoutput_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, max_length=20)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='codeEditor.file')),
            ],
        ),
    ]
