# Generated by Django 5.1.5 on 2025-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0002_remove_file_project_file_user_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='extainson',
            field=models.CharField(default='txt', max_length=10),
        ),
    ]
