# Generated by Django 5.1.5 on 2025-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0005_alter_file_content_alter_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='current_output',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
