# Generated by Django 5.1.5 on 2025-01-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0006_alter_file_current_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='current_output',
        ),
        migrations.CreateModel(
            name='CurrentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True)),
                ('Memory', models.CharField(blank=True, max_length=50)),
                ('cpuTime', models.CharField(blank=True, max_length=50)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codeEditor.file')),
            ],
        ),
    ]
