# Generated by Django 5.1.5 on 2025-01-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0007_remove_file_current_output_currentoutput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentoutput',
            old_name='Memory',
            new_name='memory',
        ),
    ]
