# Generated by Django 5.1.5 on 2025-01-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0008_rename_memory_currentoutput_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentoutput',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currentoutput', to='codeEditor.file'),
        ),
    ]
