# Generated by Django 5.1.5 on 2025-02-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0009_alter_currentoutput_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extainson',
            new_name='extension',
        ),
    ]
