# Generated by Django 5.1.5 on 2025-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeEditor', '0010_rename_extainson_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentoutput',
            name='cpuTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currentoutput',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currentoutput',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
